### ISSUE TITLE
SSE

### ISSUE THREAD

**Issue by gedw99** [delaneyj/datastar#3]
I guess it's currently using web sockets that are fed off the DB or NATS ?

It would be nice if SSE is supported due to the simple aspects of it.   

I saw a golang SSE lib thats designed to be used with NATS and other "queues".
If your interested, let me know.

**Comment by delaneyj** [comment]
No, actually the HTMX like plug-in handles EVERYTHING are SSE fragments.  Check out the examples for details.

In a NATS context I just use watchers or subs to and send fragments.  The only thing is from the front end point of view it's not technically using SSE because that only supports get whereas I'm using text stream to support put post patch delete at well, but for the back end you just treated like a normal SSE response

**Comment by gedw99** [comment]
thanks mate.

Yep I realise now that I spoke too soon and SSE is already done :) Great stuff.

Right I got ya. I saw how you make SSE work with more http verbs on the Blog when I ran the demo webui. Really clever stuff !!

will close this since e you have already done everything actually..  Easiest issue in history

**Comment by delaneyj** [comment]
So I can't use EventSource cause that only allows `GET`, so what I'm doing is using the exact same underlying `text-stream` protocol but handling the chunking and parsing in the `fetch`.  I talk about a bit in https://data-star.dev/essays/2023-11-16_event-streams-all-the-way-down

**Comment by gedw99** [comment]
Yep thanks I read that essay . Ingenious. Your platform is really clever with some forward thinking design aspects.

I am planning to extend it once I get a feel for things and make PR’s

could you make a roadmap so we can align ?

Will close this issue as it’s redundant I feel

**Comment by delaneyj** [comment]
@gedw99 right now I don't have a roadmap.  As I need things I add them but honestly its doing most of what I want right now.  But here are areas I'd like some input....

1. Types, is ther a better way to use the TS type system.  Still have so silliness in `data-model` with more `any` than I'd like
2. Better error handling... because the fragments are seen as SSE they show the EventSource ui in chrome dev tools but nothing shows up.  Want to add events so you could hook into a UI or show better details
3. Chrome extension?  Make tooling to make store and network inspection easier
4. More action helpers.  Don't think you have to go crazy but might be nice to have more helpers
5. Code review.  This was a first pass and think, while small and decently fast, could be done better with fresh eyes.

**Comment by gedw99** [comment]
This is useful to know.

Let me ponder on them and play with things more

the extension idea seems like a lot of extra work. Can’t we just do a debug window at the bottom of the gui like the htmx examples page ? Sure it can’t do as much deep introspection but it’s a good start I think to help with debugging.

**Comment by gedw99** [comment]
I guess you’re going to swap over to using the gostar package ? 

It’s looks really nice. Plain functions and type ahead coding is a huge productivity boost.

**Comment by delaneyj** [comment]
I'm exploring gostar, I think it could replace gomponents for me.  I haven't moved datastar over yet.  Also tried a version were I cached out everything and it was actually slower so didn't commit.  My next attempt is to use an ecs under the hood to make much faster and better long term

**Comment by gedw99** [comment]
ECS means  Entity component system ?

so the types

**Comment by delaneyj** [comment]
> ECS means  Entity component system ?
> 
> so the types 

Yes, would mean flattening the tree and being much better at L1 caching.  I might being going to far at it's already pretty fast for no optimizations

**Comment by gedw99** [comment]
Got ya.

from the code it’s all pure functions with the data being passed in on the function. Was wondering if you were going to use a on memory context instead of passing all data in on the function.

ironically I preferred just passing in the data to the function . Use protobufs to describe the data types. So it’s all strongly typed based on code gen. The other neat trick is to use DataSes like in c#, which are. Bit like ECS.

The other aspect to consider is the DAL.  Typically you will populate a data table type for db io and then populate a dataset with one or many data tables so that you can render a view.

**Comment by gedw99** [comment]
This discussion reminds me of Arrow a bit. There is some crossover

**Comment by delaneyj** [comment]
@gedw99 I did move over to gostar and its basically the same size as gomponents but typesafe

**Comment by gedw99** [comment]
thanks for the heads up. 

I will give it a try tonight.
